name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.1
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            build/reports/allure-report/allureReport
            build/jacoco/test/html
  
      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/allure-report/allureReport
          publish_branch: gh-pages
